// AI recommendations are generated by the backend (POST /api/ai/recommendations).
// The backend decides which provider to use (Ollama, OpenAI or mock) via its own .env,
// so no AI keys or Ollama URLs are ever exposed to the browser.

const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:3001";

export interface AIRecommendation {
  diagnosis: string;
  confidence: number;
  reasoning: string;
  prognosis: string;
  recommendations: string[];
  differentialDiagnosis: string[];
}

export async function getMedicalRecommendations(
  patientId: string,
  currentSymptoms?: string,
  apiKey?: string
): Promise<AIRecommendation> {
  const headers: Record<string, string> = { "Content-Type": "application/json" };
  if (apiKey) {
    headers["x-api-key"] = apiKey;
  } else {
    const token = localStorage.getItem("chrs_token");
    if (token) headers["Authorization"] = `Bearer ${token}`;
  }

  let res: Response;
  try {
    res = await fetch(`${API_BASE}/api/ai/recommendations`, {
      method: "POST",
      headers,
      body: JSON.stringify({ patientId, currentSymptoms }),
    });
  } catch {
    throw new Error(`Cannot reach the CHRS backend at ${API_BASE}.`);
  }

  const data = await res.json().catch(() => null);
  if (!res.ok) {
    throw new Error(data?.message || "Failed to get AI recommendations. Please try again.");
  }
  return data.recommendation;
}
